# env config
gpu: '1'
seed: 123

# dataset config
alphas: '1.0, 1.0'
batch_size: 1000
space_dim: 2
output_dim: 
data: '2gaussians'
num_totalData: 100000
sigma: 0.5

# model config
model: 'ResNet'
extraInput_dim: 1
num_innerSteps: 1
num_outerIters: 16
hidden_size: 64
num_layers: 3
activation: 'antiderivTanh'
reSampleFreq: 25
integrate_method: 'rk1'
outerTimeStep: 0.025

# training config
lr: 1e-5
optimizer: 'AdamW'
scheduler: 'StepLR'
num_iterations: 10000
weight_decay: 1e-4
step_size: 100
gamma: 0.5

# saving config
save_path: './save/wassersteinGF'